name: Continuous Intergration demo 
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@b1
        with: 
          node-version: 16
      - run: npm ci 
      - run: npm test

